### PR TITLE
add long piano to virtual piano page

### PR DESCRIPTION
**Pull request by ZichanYang324**
1. Add the long piano to the virtual-piano page
2. Add button style(including hover and active) to the button on top.
3. Create a components folder in /src directory and add css of the virtual-piano page.

https://github.com/The-Donovans-Venom-501c3/the-donovans-piano-room/assets/86720318/694a0fa8-9811-4fcb-b842-c40abfda8d5a

### CODE REVIEW

**Comment by ZichanYang324** [comment]
Change the current CSS style to tailwind


https://github.com/The-Donovans-Venom-501c3/the-donovans-piano-room/assets/86720318/4da52b50-16f7-4549-ba1a-45e2e54752f6

**Review by shubhankarval — CHANGES_REQUESTED** [review]
@ZichanYang324 Great work with setting up the audio files. However, I would like to use functional programming as much as possible, so I have changed the Short piano file. Please make the same changes in the Long Piano file and necessary changes in the page file for virtual piano.

**Comment by ZichanYang324** [comment]
@shubhankarval Both the short piano and long piano have been modified and the responsiveness issue also has been fixed, please check.

**Review by shubhankarval — APPROVED** [review]
Great work @ZichanYang324!

**Pull request merged**
