### PR TITLE
Standardized headers size and font and added links to the footer. Ensured consistent padding.

### PR DESCRIPTION
**Pull request by KavinKarthik-git**

### CODE REVIEW

**Review by aouiniamine — CHANGES_REQUESTED** [review]
The about section headers is a little big change the text to -> text-6xl 3xl:text-7xl 4xl:text-8xl

**Comment by KavinKarthik-git** [comment]
> The about section headers is a little big change the text to -> text-6xl 3xl:text-7xl 4xl:text-8xl

I've Implemented hover effects and updated About section headers as you mentioned. Please review

**Review by aouiniamine — CHANGES_REQUESTED** [review]
so far so good, 
You also need to setup the hover effects for the Auth Navbar and buttons.
You may have an issue with the cart because it's an SVG you can use: 
import ShoppingCartOutlinedIcon from'@mui/iconsmaterial/ShoppingCartOutlined';
and change the text color as needed for the hover effect and standard color.

**Comment by KavinKarthik-git** [comment]
I've Implemented hover effects to the Navber as you mentioned. Please review @aouiniamine

**Review by aouiniamine — APPROVED** [review]

**Pull request merged**
